#!/bin/bash

#SERVER=links.services.disqus.com
#SERVER=c.disquscdn.com 
#SERVER=www.linkedin.com

SERVER=wikiszotar.hu


openssl s_client \
    -servername  $SERVER \
    -verify      1 \
    -connect     $SERVER:443
